djangoProjectGroup/urls.py
# Tafshi Uthshow Hoque, Rafael Rojas Vivanc & Rishabh Kabawala
# Project-level urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from inventory.views import download_report

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('', RedirectView.as_view(pattern_name='inventory:login', permanent=False)),
    path('report/download/<int:pk>/', download_report, name='download_report'),
    path('inventory/', include('inventory.urls')),  # Include the 'inventory' app URLconf
    # ... any other project-level URL patterns
]

inventory/urls.py
# Tafshi Uthshow Hoque, Rafael Rojas Vivanc & Rishabh Kabawala
# App-level urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import download_report, download_inventory_report

app_name = 'inventory'  # Define the app namespace

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='inventory:login'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('successful-registration/', views.successful_registration, name='successful_registration'),
    path('home/', views.home, name='home'),
    path('equipment/', views.EquipmentListView.as_view(), name='equipment_list'),
    path('reserve/', views.ReservationCreateView.as_view(), name='reserve_equipment'),
    path('booking/', views.booking_view, name='booking_view'),
    path('cancel-reservation/<int:pk>/', views.cancel_reservation, name='cancel_reservation'),
    path('edit-account/', views.edit_account, name='edit_account'),
    path('report/download/<int:pk>/', download_report, name='download_report'),
    path('report/download-inventory/', download_inventory_report, name='download_inventory_report'),

    # Add other patterns as needed
]

inventory/models.py
# Tafshi Uthshow Hoque, Rafael Rojas Vivanco & Rishabh Kabawala

# models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # date_of_birth = models.DateField(null=True, blank=False) Notice in development that the DOB is not needed.
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'


class Location(models.Model):
    class LocationList(models.TextChoices):
        OTHER = 'Other', _('Other')
        XRLab_Blue_Cabinet = 'XRLab Blue Cabinet', _('XRLab Blue')
        XRLab_Blue_Cabinet_Large = 'XRLab Blue Cabinet Large', _('XRLab Blue Cabinet Large')
        XRLab_Medium_Wooden_Cabinet = 'XRLab Medium Wooden Cabinet', _('XRLab Medium Wooden Cabinet')

    location_name = models.CharField(max_length=255, null=True, blank=True, default="Default Location")
    location_type = models.CharField(max_length=50, choices=LocationList.choices, default="")

    def __str__(self):
        return f'{self.location_name}'


# Done
class Equipment(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    type = models.CharField(max_length=100, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True)
    last_audit = models.DateField(null=True)
    location = models.ForeignKey('Location', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=100, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    availability = models.BooleanField(default=True)
    onsite_only = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.quantity <= 0:
            self.availability = False
        else:
            self.availability = True

        super(Equipment, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.type})"


class Reservation(models.Model):
    class ReservationStatus(models.TextChoices):
        PENDING = 'Pending', _('Pending')
        APPROVED = 'Approved', _('Approved')
        REJECTED = 'Rejected', _('Rejected')
        CANCELED = 'Canceled', _('Canceled')

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservations')
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='reservations')
    start_date = models.DateField()
    end_date = models.DateField()
    status = models.CharField(max_length=20, choices=ReservationStatus.choices, default=ReservationStatus.PENDING)
    purpose = models.TextField()
    quantity = models.IntegerField(default=0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_status = self.status

    def save(self, *args, **kwargs):
        # Check if the status has been changed to 'Canceled'
        if (self.pk and self.status == self.ReservationStatus.CANCELED and self.__original_status !=
                self.ReservationStatus.CANCELED):
            # Increment the equipment's quantity by the canceled reservation's quantity
            self.equipment.quantity += self.quantity
            self.equipment.save()

        super().save(*args, **kwargs)
        self.__original_status = self.status  # Update the original status after saving

    def __str__(self):
        return f'{self.user.username} - {self.equipment.name}'


class EquipmentUsageHistory(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    times_reserved = models.IntegerField(default=0)
    last_reserved = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.equipment.name} usage history"


# Update the Reservation model's safe method to increment the times_reserved
@receiver(post_save, sender=Reservation)
def update_usage_history(sender, instance, created, **kwargs):
    if created:
        history, _ = EquipmentUsageHistory.objects.get_or_create(equipment=instance.equipment)
        history.times_reserved += 1
        history.last_reserved = instance.start_date
        history.save()

inventory/forms.py
# Tafshi Uthshow Hoque & Rafael Rojas Luppichini
# forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Reservation, Equipment
from django.core.exceptions import ValidationError
from django.utils import timezone


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    # date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("A user with that email already exists.")
        return email

    # def clean_date_of_birth(self):
    #     date_of_birth = self.cleaned_data.get('date_of_birth')
    #     today = datetime.date.today()
    #     age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))
    #     if age < 18:
    #         raise ValidationError("You must be at least 18 years old to register.")
    #     return date_of_birth


class ReservationForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'min': timezone.now().date()}))

    class Meta:
        model = Reservation
        fields = ['equipment', 'start_date', 'purpose', 'quantity']

    def clean_start_date(self):
        start_date = self.cleaned_data.get('start_date')
        if start_date < timezone.now().date():
            raise forms.ValidationError("The start date must be today or in the future.")

        return start_date


class EquipmentForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = '__all__'

inventory/views.py
# Tafshi Uthshow Hoque, Rafael Rojas Vivanc & Rishabh Kabawala
# views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
import datetime

from .forms import UserRegisterForm, ReservationForm
from .models import Equipment, Reservation, UserProfile, Location, EquipmentUsageHistory


# Authentication and Registration Views

@login_required
def home(request):
    return render(request, 'inventory/home.html')


@login_required
def edit_account(request):
    return render(request, "registration/editAccount.html")


class RegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('inventory:successful_registration')

    def form_valid(self, form):
        user = form.save()
        UserProfile.objects.update_or_create(user=user, defaults={'is_approved': False})
        return super().form_valid(form)

    def form_invalid(self, form):
        return super(RegisterView, self).form_invalid(form)


# Equipment Views

class EquipmentListView(LoginRequiredMixin, ListView):
    model = Equipment
    context_object_name = 'equipment_list'
    template_name = 'inventory/equipment_list.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        equipment_types = Equipment.objects.values_list('type', flat=True).distinct()
        equipment_locations = Location.objects.values_list('location_name', flat=True).distinct()

        # Add to context
        context['equipment_types'] = equipment_types
        context['equipment_locations'] = equipment_locations
        return context


# Reservation Views

@login_required
def booking_view(request):
    # Fetch reservations for the logged-in user and order them by start date
    reservations = (Reservation.objects.filter(user=request.user).select_related('equipment', 'equipment__location')
                    .order_by('-start_date'))
    return render(request, 'inventory/bookingList.html', {'reservations': reservations})


@login_required
def cancel_reservation(request, pk):
    try:
        reservation = Reservation.objects.get(pk=pk, user=request.user)
        if reservation.status not in [Reservation.ReservationStatus.APPROVED, Reservation.ReservationStatus.PENDING]:
            messages.error(request, "Cannot cancel a reservation that is not pending or approved.")
        else:
            equipment = reservation.equipment
            equipment.quantity += reservation.quantity  # Restore the equipment quantity
            equipment.save()
            reservation.delete()
            messages.success(request, "Reservation cancelled successfully.")
    except Reservation.DoesNotExist:
        messages.error(request, "Reservation not found.")
    return HttpResponseRedirect(reverse('inventory:booking_view'))


class ReservationCreateView(LoginRequiredMixin, CreateView):
    model = Reservation
    form_class = ReservationForm
    template_name = 'inventory/bookingList.html'
    success_url = reverse_lazy('inventory:booking_view')

    def form_valid(self, form):
        form.instance.user = self.request.user
        reservation = form.save(commit=False)
        equipment = reservation.equipment
        start_date = form.cleaned_data['start_date']

        reservation.end_date = start_date + datetime.timedelta(days=7)

        if equipment.quantity >= reservation.quantity:
            equipment.quantity -= reservation.quantity
            equipment.save()
            messages.success(self.request, "Reservation successfully created.")
            return super().form_valid(form)
        else:
            form.add_error('quantity', 'Insufficient quantity available.')
            return self.form_invalid(form)


# Miscellaneous Views

def successful_registration(request):
    return render(request, 'registration/successfulRegistration.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            try:
                user_profile = UserProfile.objects.get(user=user)
                if user_profile.is_approved:
                    login(request, user)
                    return redirect('inventory:home')
                else:
                    messages.error(request, 'Your account is pending approval.')
            except UserProfile.DoesNotExist:
                messages.error(request, 'User profile does not exist.')
        else:
            messages.error(request, 'Invalid username or password.')

    return render(request, 'registration/login.html')


@login_required
@staff_member_required
def download_report(request, pk):
    equipment_usage_history = EquipmentUsageHistory.objects.get(pk=pk)

    response = HttpResponse(content_type='application/pdf')
    response[
        'Content-Disposition'] = f'attachment; filename="{equipment_usage_history.equipment.name}_usage_report.pdf"'

    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    y_position = height - inch * 1
    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch * 0.5, y_position, f"Usage Report for: {equipment_usage_history.equipment.name}")

    line_height = 0.2 * inch
    x_position = inch * 0.5
    y_position -= 2 * line_height

    p.setFont("Helvetica", 11)
    p.drawString(x_position, y_position, f"Times Reserved: {equipment_usage_history.times_reserved}")
    y_position -= line_height

    if equipment_usage_history.last_reserved:
        p.drawString(x_position, y_position,
                     f"Last Reserved On: {equipment_usage_history.last_reserved.strftime('%Y-%m-%d')}")
        y_position -= line_height

    p.showPage()
    p.save()
    return response


@login_required
@staff_member_required
def download_inventory_report(request):
    equipment_list = Equipment.objects.all().select_related('location')

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="inventory_report.pdf"'

    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    # Starting Y position near the top of the page
    y_position = height - inch * 1
    line_height = 0.2 * inch  # Define the space needed for each line, including some space between lines

    # Define columns positions based on the page width
    column_1_x = inch * 0.5
    column_2_x = width / 4
    column_3_x = width / 2
    column_4_x = width / 5 * 3 + 60

    # Print header
    p.setFont("Helvetica-Bold", 14)
    p.drawString(column_1_x, y_position, "Inventory Report")
    y_position -= inch / 2

    p.setFont("Helvetica-Bold", 10)
    p.drawString(column_1_x, y_position, "Equipment Name")
    p.drawString(column_2_x, y_position, "Type")
    p.drawString(column_3_x, y_position, "Quantity")
    p.drawString(column_4_x, y_position, "Location")
    y_position -= line_height  # Move to the next line for equipment entries

    p.setFont("Helvetica", 7)

    # Iterate through the equipment list and write to the PDF
    for equipment in equipment_list:
        # Check if we need to start a new page
        if y_position < inch:
            p.showPage()
            y_position = height - inch * 1  # Reset y_position for the new page
            p.setFont("Helvetica", 7)

        p.drawString(column_1_x, y_position, f"{equipment.name}")
        p.drawString(column_2_x, y_position, f"{equipment.type}")
        p.drawString(column_3_x, y_position, f"{equipment.quantity}")
        p.drawString(column_4_x, y_position, f"{equipment.location}")

        y_position -= line_height  # Decrement the y_position for the next line

    p.showPage()
    p.save()
    return response

templates/inventory/base.html
<!--Simona Bosilkova -->

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Django Project{% endblock %}</title>
    <style>
        html {
          height: 100%;
          box-sizing: border-box;
        }

        *, *:before, *:after {
          box-sizing: inherit;
        }

        body {
          display: flex;
          flex-direction: column;
          min-height: 100%;
          margin: 0;
        }

        /* Additional styles for navigation bar */
        nav {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        nav ul {
            display: flex;
            list-style-type: none;
            margin: 0;
            padding: 0;
            align-items: center;
            justify-content: center;
        }
        nav ul li {
            margin-right: 20px;
            margin-left: 20px;
        }


        nav ul li a, nav ul li button {
            font-size: 1em;
            line-height: 1.5em;
            text-decoration: none;
            color: rgb(252, 163, 17);
            padding: 0.25em 1em;
            border: none;
            background: none;
            cursor: pointer;
        }

        /* Additional reset for forms to remove any browser-specific padding/margins */
        nav ul li form {
            padding: 0;
            margin: 0;
            display: inline;
        }

        /* Additional reset for buttons to remove any browser-specific padding/margins */
        nav ul li button {
            font-family: inherit;
            font-size: inherit;
            vertical-align: middle;
        }


        nav ul li form button {
            padding: 0.25em 1em;
            margin: 0;
            border: none;
            background: none;
            color: rgb(252, 163, 17);
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
            vertical-align: middle;
        }

        /* Updated hover effect for consistency */
        nav ul li a:hover, nav ul li button:hover {
            color: rgb(134, 87, 5);
        }

        main {
          flex: 1 0 auto;
          padding-bottom: 150px;
        }

        footer {
          text-align: center;
          color: white;
          padding: 5px 0;
          width: 100%;
        }
    </style>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'inventory:home' %}">Home</a></li>
                <li><a href="{% url 'inventory:equipment_list' %}">Equipment List</a></li>
                <li><a href="{% url 'inventory:booking_view' %}">View My Bookings</a></li>
                <li><a href="{% url 'inventory:edit_account' %}">Update Account Info</a></li>
                <li>
                    <form action="{% url 'inventory:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- Content goes here -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Django Project. All rights reserved.</p>
    </footer>
</body>
</html>

templates/inventory/bookingList.html
<!--Simona Bosilkova -->
{% extends 'inventory/base.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'bookingList.css' %}">
{% endblock %}

{% block content %}
<div class="content">
    <h1>My Bookings List</h1>
    <table class="booking-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Equipment</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Location</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in reservations %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.status }}</td>
                <td>{{ booking.equipment.name }}</td>
                <td>{{ booking.start_date }}</td>
                <td>{{ booking.end_date }}</td>
                <td>{{ booking.equipment.location.location_name }}</td>
                <td>
                    {% if booking.status in "Pending Approved" %}
                    <form action="{% url 'inventory:cancel_reservation' booking.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cancel</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No bookings found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/inventory/equipment_list.html
<!-- Tafshi Uthshow Hoque, Rafael Rojas Vivanco & Simona Bosilkova -->
{% extends 'inventory/base.html' %}

{% load static %}

{% block title %}Equipment List{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'equipmentList.css' %}">
{% endblock %}

{% block content %}
<!-- Equipment List Display -->
<div class="content">
    <h1>Equipment List</h1>
    <button class="filter-button">Filter list</button>
    <table class="equipment-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Availability</th>
                <th>Quantity</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            {% for equipment in equipment_list %}
            <tr onclick="showDetailsModal(this)" data-equipment-id="{{ equipment.id }}" data-equipment-name="{{ equipment.name }}" data-equipment-type="{{ equipment.type }}" data-equipment-availability="{{ equipment.availability|yesno:'Available,Not Available' }}" data-equipment-location="{{ equipment.location.location_name }}" data-equipment-quantity="{{ equipment.quantity }}">
                <td>{{ equipment.name }}</td>
                <td>{{ equipment.type }}</td>
                <td>{{ equipment.availability|yesno:"Available, Not Available" }}</td>
                <td>{{ equipment.quantity }}</td>
                <td>{{ equipment.location.location_name }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">No equipment found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
    
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    
<!-- Equipment Reservation Modal -->
<div id="equipmentDetailsModal" class="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <span class="close">&times;</span>
            <div class="modal-header">
                <h5 class="modal-title">Reserve Equipment</h5>
            </div>
            <div class="modal-body">
                <form id="reservation-form" method="POST" action="{% url 'inventory:reserve_equipment' %}">
                    {% csrf_token %}
                    <input type="hidden" name="equipment" id="modal-equipment-id-hidden">
                    <div>Equipment Name: <span id="modal-equipment-name"></span></div>
                    <div>Type: <span id="modal-equipment-type"></span></div>
                    <div>Availability: <span id="modal-equipment-availability"></span></div>
                    <div>Location: <span id="modal-equipment-location"></span></div>
                    <br>
                    <label for="quantity-required">Quantity:</label>
                    <input type="number" id="quantity-required" name="quantity" min="1" placeholder="Enter quantity" required>
                    <label for="start-date">Start Date:</label>
                    <input type="date" id="start-date" name="start_date" min="{{ today }}" required>
                    <label>
                        <textarea id="purpose" name="purpose" placeholder="Purpose of reservation" required></textarea>
                    </label>
                    <button type="submit" class="btn-btn-primary">Reserve</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Filter Modal -->
<div id="filterModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Filter equipment</h2>
        <form id="filterForm" method="get" action="{% url 'inventory:equipment_list' %}">
            <label for="equipment-name">Equipment name:</label>
            <input type="text" id="equipment-name" name="name" placeholder="Enter equipment name">
            <label for="type">Type:</label>
            <select id="type" name="type">
                <option value="">Select type</option>
                {% for type in equipment_types %}
                <option value="{{ type }}">{{ type }}</option>
                {% endfor %}
            </select>
            <label for="availability">Availability:</label>
            <select id="availability" name="availability">
                <option value="">Select availability</option>
                <option value="Available">Available</option>
                <option value="Not Available">Not Available</option>
            </select>
            <label for="location">Location:</label>
            <select id="location" name="location">
                <option value="">Select location</option>
                {% for location in equipment_locations %}
                <option value="{{ location }}">{{ location }}</option>
                {% endfor %}
            </select>
            <button type="submit" id="applyFilters">Apply filters</button>
        </form>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    let today = new Date().toISOString().split('T')[0];
    document.getElementById('start-date').setAttribute('min', today);

    let filterModal = document.getElementById("filterModal");
    let detailsModal = document.getElementById("equipmentDetailsModal");
    let filterBtn = document.querySelector(".filter-button");
    let closeButtons = Array.from(document.getElementsByClassName("close"));

    closeButtons.forEach(btn => {
        btn.onclick = function() {
            btn.closest('.modal').style.display = "none";
        }
    });

    filterBtn.onclick = function() {
        filterModal.style.display = "block";
    };

    window.onclick = function(event) {
        if (event.target === filterModal) {
            filterModal.style.display = "none";
        }
        if (event.target === detailsModal) {
            detailsModal.style.display = "none";
        }
    };

    document.getElementById('applyFilters').addEventListener('click', function(event) {
        event.preventDefault();
        applyFilters();
        filterModal.style.display = 'none';
    });
});

function applyFilters() {
    let nameFilter = document.getElementById('equipment-name').value.toLowerCase();
    let typeFilter = document.getElementById('type').value;
    let availabilityFilter = document.getElementById('availability').value;
    let locationFilter = document.getElementById('location').value;

    let table = document.querySelector('.equipment-table tbody');
    let rows = table.querySelectorAll('tr');

    rows.forEach(row => {
        let name = row.cells[0].textContent.toLowerCase().trim();
        let type = row.cells[1].textContent.trim();
        let availability = row.cells[2].textContent.trim();
        let location = row.cells[4].textContent.trim();

        let nameMatch = !nameFilter || name.includes(nameFilter);
        let typeMatch = !typeFilter || type === typeFilter;
        let availabilityMatch = !availabilityFilter || availability.includes(availabilityFilter);
        let locationMatch = !locationFilter || location.includes(locationFilter);

        row.style.display = (nameMatch && typeMatch && availabilityMatch && locationMatch) ? '' : 'none';
    });
}

function showDetailsModal(row) {
    let detailsModal = document.getElementById("equipmentDetailsModal");

    let equipmentId = row.getAttribute('data-equipment-id');
    let equipmentName = row.getAttribute('data-equipment-name');
    let equipmentType = row.getAttribute('data-equipment-type');
    let equipmentAvailability = row.getAttribute('data-equipment-availability');
    let equipmentLocation = row.getAttribute('data-equipment-location');
    let equipmentQuantity = row.getAttribute('data-equipment-quantity');

    document.getElementById('modal-equipment-id-hidden').value = equipmentId;
    document.getElementById('modal-equipment-name').textContent = equipmentName;
    document.getElementById('modal-equipment-type').textContent = equipmentType;
    document.getElementById('modal-equipment-availability').textContent = equipmentAvailability;
    document.getElementById('modal-equipment-location').textContent = equipmentLocation;
    document.getElementById('quantity-required').max = equipmentQuantity;

    detailsModal.style.display = 'block';
}
</script>
{% endblock %}

templates/inventory/home.html
<!-- home.html -->
<!-- Sophie Earish -->
{% extends 'inventory/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="img-container">
        <img src="{% static 'images/Yhuens_Vault.png' %}" alt="Vault Image" />
    </div>
    <h1>Welcome to the CSE Equipment Inventory System</h1>
    <h3>Let's get started...</h3>
   <div class="card-container">
  <a href="{% url 'inventory:equipment_list' %}" class="card-link" aria-label="View Equipment List">
    <div class="card">
      <p class="card-text">Equipment List</p>
    </div>
  </a>
  <a href="{% url 'inventory:booking_view' %}" class="card-link" aria-label="View My Bookings">
    <div class="card">
      <p class="card-text">View My Bookings</p>
    </div>
  </a>
  <a href="{% url 'inventory:edit_account' %}" class="card-link" aria-label="Update Account Info">
    <div class="card">
      <p class="card-text">Update Account Info</p>
    </div>
  </a>
</div>
</div>
{% endblock content %}